@host = http://localhost:3000

### Obtener todos los teachers
GET {{host}}/api/teachers

### Filtrar teachers
POST {{host}}/api/teachers/filter
Content-Type: application/json

{
    "knowledge": "",
    "schedule": "Mañana",
    "minPrice": 20,
    "maxPrice": 100,
    "orderOption": "Mejor Valoracion",
    "name": "Al"
}